# Generated by Django 3.0.4 on 2020-03-27 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_comment_commentcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commentDate'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
